services:
  mongodb:
    image: mongo:latest
    container_name: rtsp-mongodb
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rtsp_management
    restart: unless-stopped
  
  redis:
    image: redis:latest
    container_name: rtsp-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
    name: rtsp-mongodb-data
  redis_data:
    name: rtsp-redis-data